ci: update Node.js setup and add version check

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -14,11 +14,28 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - name: Setup Node.js v20.x
+      - name: Setup Node.js
         uses: actions/setup-node@v4
         with:
-          node-version: "20.x"
+          node-version-file: ".nvmrc"
           cache: "yarn"
+
+      - name: Check Node version
+        shell: bash
+        run: |
+          NVM_NODE_VERSION=$(cat .nvmrc)
+          VOLTA_NODE_VERSION=$(node -p "require('./package.json').volta.node")
+
+          echo "Checking Node.js versions in .nvmrc and package.json (volta)..."
+          echo "NVM: $NVM_NODE_VERSION"
+          echo "Volta: $VOLTA_NODE_VERSION"
+
+          if [ "$VOLTA_NODE_VERSION" != "$NVM_NODE_VERSION" ]; then
+            echo "Error: Node.js versions in .nvmrc and package.json (volta) do not match."
+            exit 1
+          else
+            echo "Check passed!"
+          fi
 
       - name: Install dependencies
         run: yarn install --immutable
